### PR TITLE
Updated AboutUs

### PR DESCRIPTION
**Pull request by J87**
Hello Jay,
Please see pull request. Tried a couple of times from the bash console, but I don't think it was working.  Instead, I used the online button to create a pull request.

Thanks,
Justin Hoffman

### CODE REVIEW

**Comment by jgendron** [comment]
Justin. It worked beautifully. This is good practice for us all. Jay

On Monday, December 28, 2015, J87 notifications@github.com wrote:

> Hello Jay,
> Please see pull request. Tried a couple of times from the bash console,
> but I don't think it was working. Instead, I used the online button to
> create a pull request.
> 
> Thanks,
> 
> ## Justin Hoffman
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/TechTank-DataScience/WeAreCohort/pull/4
> Commit Summary
> - Updated AboutUs
> 
> File Changes
> - _M_ AboutUs.md
>   https://github.com/TechTank-DataScience/WeAreCohort/pull/4/files#diff-0
>   (9)
> 
> Patch Links:
> - https://github.com/TechTank-DataScience/WeAreCohort/pull/4.patch
> - https://github.com/TechTank-DataScience/WeAreCohort/pull/4.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TechTank-DataScience/WeAreCohort/pull/4.

## 

Sincerely,

Gerald "Jay" Gendron
(757) 372-5746 (cell)
gerald.gendron@gmail.com

 http://www.linkedin.com/in/jaygendron

**Comment by J87** [comment]
I thought it might.  I wonder why it won’t notify you of a pull request when I pull from the cloned repo though the terminal/console.

Will have to look that up.

Thanks!
Justin

**Comment by BoozAllenTechTank** [comment]
You know...when you pull from your console you are telling Git to pull down the latest information from the remote repo into your local, cloned copy.

That's why the web interface has a pull request, because it has to pull up from your local.

There is documentation at the [git-scm site](https://git-scm.com/docs/git-request-pull) that shows how to initiate a pull request from the console using `git request-pull` and some parameters

**Comment by J87** [comment]
Perfect! I'll try this next time.
-J

**Comment by jgendron** [comment]
...there is a trend fm towards more web GUI operations with Git. Either is
a win. Jay

On Wednesday, December 30, 2015, J87 notifications@github.com wrote:

> Perfect! I'll try this next time.
> -J
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TechTank-DataScience/WeAreCohort/pull/4#issuecomment-168016675
> .

## 

Sincerely,

Gerald "Jay" Gendron
(757) 372-5746 (cell)
gerald.gendron@gmail.com

 http://www.linkedin.com/in/jaygendron

**Pull request merged**
